import Sidebar from '@/components/Sidebar';
import './globals.css'
import { Figtree } from 'next/font/google'

const font = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export const revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const products = await getActiveProductsWithPrices();
  // const userSongs = await getSongsByUserId();

  return (
    <html lang="en">
      <body className={font.className}>
        <Sidebar 
          // songs={}
        >
          {children}
        </Sidebar>
      </body>
    </html>
  )
}
