import { Figtree } from 'next/font/google';

// import getSongsByUserId from '@/actions/getSongsByUserId'
// import getActiveProductsWithPrices from '@/actions/getActiveProductsWithPrices'
import Sidebar from '@/components/Sidebar';
// import Player from '@/components/Player'
import SupabaseProvider from '@/providers/SupabaseProvider';
import UserProvider from '@/providers/UserProvider';
import ModalProvider from '@/providers/ModalProvider';
import ToasterProvider from '@/providers/ToasterProvider';
import './globals.css'

const font = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export const revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const products = await getActiveProductsWithPrices();
  // const userSongs = await getSongsByUserId();

  return (
    <html lang="en">
      <body className={font.className}>
      <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider 
              // products={products}
            />
            <Sidebar 
              // songs={}
            >
              {children}
            </Sidebar>
            {/* <Player /> */}
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
